name: workflow_01
on:
  workflow_dispatch:
     inputs:
      Workflow_2:
        description: 'Workflow 2 which will be triggered'
        required: true
        default: 'Run Selenium On GitHub Action'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'JamiEmersonUTS'

      workflow2_repo_github:
        description: 'repository'
        required: true
        default: 'selenium-github-actions'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <ACTIONS_KEY>"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/JamiEmersonUTS/selenium-github-actions/dispatches \
            -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
      - uses: actions/checkout@v3
