name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: JamiEmersonUTS
          repo: selenium-github-actions
          github_token: ${{ secrets.ACTIONS_KEY }}
          workflow_file_name: Selenium-Action_Template.yaml
          ref: main
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
